name: clip_forge
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22
  - cython=0.29
  - pytorch=1.13
  - torchvision
  - imageio=2.21
  - numpy=1.24
  # - numpy-base=1.24
  - matplotlib=3.6
  - matplotlib-base=3.6
  - pandas=1.5
  - pillow=9.4
  # - pyembree=0.1.4
  - seaborn=0.12
  - pytest=7.2
  - pyyaml=6
  - scikit-image=0.19
  - scipy=1.10
  - tensorboardx=2.5
  - tqdm=4.64
  - trimesh=3.18
  - h5py=3.8
  - plyfile=0.7
  - scikit-learn=1.2
  - pip:
    - git+https://github.com/openai/CLIP.git